name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pip install pytest
          python -m pytest
